//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Base.Server.Model
{
    public partial class FinanceiroEntities : ObjectContext
    {
        public const string ConnectionString = "name=FinanceiroEntities";
        public const string ContainerName = "FinanceiroEntities";
    
        #region Constructors
    
        public FinanceiroEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public FinanceiroEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public FinanceiroEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<AccountsPayable> AccountsPayable
        {
            get { return _accountsPayable  ?? (_accountsPayable = CreateObjectSet<AccountsPayable>("AccountsPayable")); }
        }
        private ObjectSet<AccountsPayable> _accountsPayable;
    
        public ObjectSet<PaidAccount> PaidAccount
        {
            get { return _paidAccount  ?? (_paidAccount = CreateObjectSet<PaidAccount>("PaidAccount")); }
        }
        private ObjectSet<PaidAccount> _paidAccount;
    
        public ObjectSet<Provider> Provider
        {
            get { return _provider  ?? (_provider = CreateObjectSet<Provider>("Provider")); }
        }
        private ObjectSet<Provider> _provider;
    
        public ObjectSet<User> User
        {
            get { return _user  ?? (_user = CreateObjectSet<User>("User")); }
        }
        private ObjectSet<User> _user;

        #endregion
    }
}
