//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Base.Server.Model
{
    public partial class Provider
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string Phone
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string Site
        {
            get;
            set;
        }
    
        public virtual string Contato
        {
            get;
            set;
        }
    
        public virtual int UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    if (User != null && User.Id != value)
                    {
                        User = null;
                    }
                    _userId = value;
                }
            }
        }
        private int _userId;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<AccountsPayable> AccountsPayable
        {
            get
            {
                if (_accountsPayable == null)
                {
                    var newCollection = new FixupCollection<AccountsPayable>();
                    newCollection.CollectionChanged += FixupAccountsPayable;
                    _accountsPayable = newCollection;
                }
                return _accountsPayable;
            }
            set
            {
                if (!ReferenceEquals(_accountsPayable, value))
                {
                    var previousValue = _accountsPayable as FixupCollection<AccountsPayable>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupAccountsPayable;
                    }
                    _accountsPayable = value;
                    var newValue = value as FixupCollection<AccountsPayable>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupAccountsPayable;
                    }
                }
            }
        }
        private ICollection<AccountsPayable> _accountsPayable;
    
        public virtual User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    var previousValue = _user;
                    _user = value;
                    FixupUser(previousValue);
                }
            }
        }
        private User _user;

        #endregion
        #region Association Fixup
    
        private void FixupUser(User previousValue)
        {
            if (previousValue != null && previousValue.Provider.Contains(this))
            {
                previousValue.Provider.Remove(this);
            }
    
            if (User != null)
            {
                if (!User.Provider.Contains(this))
                {
                    User.Provider.Add(this);
                }
                if (UserId != User.Id)
                {
                    UserId = User.Id;
                }
            }
        }
    
        private void FixupAccountsPayable(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (AccountsPayable item in e.NewItems)
                {
                    item.Provider = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (AccountsPayable item in e.OldItems)
                {
                    if (ReferenceEquals(item.Provider, this))
                    {
                        item.Provider = null;
                    }
                }
            }
        }

        #endregion
    }
}
